### ISSUE TITLE
MPL

### ISSUE THREAD

**Issue by jfcg** [cncf/foundation#104]
Greetings,

Is there a spesific reason that [MPL](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) is out of the [Allowlist](https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md)?
Afaik it is an [OSI](https://opensource.org/licenses) approved license from Mozilla, and it is open source/closed source/commercial etc. friendly.

Thanks..

**Comment by caniszczyk** [comment]
The simple answer is that it's a weak copy left license versus a permissive one, which we don't allow by default.

We could go for an exception if you and the Prometheus team wishes.

You're the only contributor so you can easily re-license the code to another license. For your troubles, happy to send you a bunch of Prometheus swag if that was your thing, but all up to you: https://store.cncf.io/collections/prometheus

**Comment by jfcg** [comment]
turns out it is probably not a much-needed feature according to prometheus team.
mpl software can be included with the exception mechanism, so closing.
thanks..
