### ISSUE TITLE
Update "Keep Cloud Native Well" program with OSMI to reflect the move to virtual

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#107]

**Comment by caniszczyk** [comment]
This is being worked on for KubeCon NA 2021 by the events team!

**Comment by arun-gupta** [comment]
can we keep the ticket open until a link is available?

**Comment by caniszczyk** [comment]
@arun-gupta np!

**Comment by krook** [comment]
@arun-gupta is this good to close?

**Comment by arun-gupta** [comment]
yep, this is dated and not relevant any more.
