### ISSUE TITLE
Code Search for CNCF Projects

### ISSUE THREAD

**Issue by Pothulapati** [cncf/foundation#113]
## Introduction

CNCF currently has a really powerful set of developer tools that makes contributors life easier. Starting from [Project](https://github.com/kubernetes/test-infra) [Specific workflow](https://github.com/kubernetes/test-infra/tree/master/prow)  [tools](https://github.com/prometheus/test-infra) to [Common Project-level Monitoring tools](https://devstats.cncf.io/), there are a wide array of tools helping developers in their daily jobs. One such tool that I can think of, that has immense value is **Code Search**

CodeSearch is becoming an important tool in developer's workflow, As it makes navigating code easier, more accessible, and faster (through Browser). Its importance is compounded when there are multiple repositories having dependencies between each other (as its the case with CNCF). It also makes it easy to understand what repo's are using which versions of dependencies and which code paths.

## Benefits

CNCF has a lot of projects that have inter-related dependencies i.e Most projects depend on k8s `client-go`, etc

- Makes Code Search and Navigation easier, without having to set up dev environments specific to the project.
- Makes it easier to understand project dependencies (both inside and outside CNCF), and navigating between them.
- Easier to search for code-paths across repositories, useful for understanding the effects of breaking changes, etc.

## Examples

- [Kubernetes Code Search](https://cs.kubernetes.io/)
- [Google OSS](https://source.chromium.org/)
- [Debian Code Search](https://codesearch.debian.net/)
- [SourceGraph Global Instance](https://sourcegraph.com/search)

## Conclusion

I personally have been a heavy user of both [Kubernetes Code Search](https://cs.kubernetes.io/) and [SourceGraph Global Instance](https://sourcegraph.com/search) and feel that it is really valuable to have a **hosted Code Search engine specifically for CNCF projects.** 

If there is similar interest from CNCF and other contributors/users. We can start looking for OSS Code Search Engines available and how we can take this effort forward.

@caniszczyk

**Comment by raukadah** [comment]
Hound is also pretty awesome tool for self hosted codesearch solution  https://github.com/hound-search/hound . In OpenStack & RDO community uses it.
* http://codesearch.openstack.org/
* https://review.rdoproject.org/codesearch/

**Comment by justaugustus** [comment]
I love this idea!

**Comment by caniszczyk** [comment]
I'll work on this, I already know the folks there well.

Note, this kind of currently exists via https://sourcegraph.com/search?q=repogroup:cncf+config&patternType=regexp

However, we can do a nicer landing page and so on, stay tuned.

**Comment by Pothulapati** [comment]
@caniszczyk That's awesome to hear! :+1: 
I am happy to help if there is any need!

**Comment by sqs** [comment]
@caniszczyk: The nicer landing page for CNCF code search is up! https://sourcegraph.com/cncf

We're tracking the work in https://github.com/sourcegraph/sourcegraph/issues/14318 on our side (cc and thanks to @poojaj-tech @limitedmage @attfarhan @lguychard @bobheadxi). Some TODOs still on our end include:

- setting up precise ([LSIF-based](https://lsif.dev/), eg using [lsif-go](https://github.com/sourcegraph/lsif-go)) code intelligence for definitions/references on these repositories (current progress: ~50% of repositories have this set up)
- exposing the full and up-to-date list of repositories being searched (easter egg: if you click the search without typing in any query, you'll see the full list of repositories)
- automatically updating the list of repositories to search when projects get added/renamed/removed from CNCF
- removing tracking cookies from this landing page (and thus the annoying cookie notice)
- etc.

What do you all think? All feedback is appreciated. We want to make this perfect for CNCF.

![image](https://user-images.githubusercontent.com/1976/95099067-4da68180-06e4-11eb-9b49-161fef9ff788.png)

**Comment by caniszczyk** [comment]
I'll consider this closed for now given that the site is up, please offer feedback here: https://github.com/sourcegraph/sourcegraph/issues/14318

Thanks for the idea @Pothulapati and thanks to sourcegraph for the tool :)
