### ISSUE TITLE
Code of Conduct in non-English languages

### ISSUE THREAD

**Issue by castrojo** [cncf/foundation#15]
We'd like to set up regional boards for users on discuss.kubernetes.io in their own native languages but we're missing a code of conduct in Chinese for example. 

I'm not sure what the protocol is, but I figured it wouldn't hurt to consider having the CoC translated to other languages. Some data that we have, the top 5 non-English kubernetes slack channels are currently:

- jp-users - 783
- de-users - 441
- fr-users - 407
- cn-users - 357
- es-users - 204

**Comment by mrbobbytables** [comment]
This might be resolved if CoC is updated to the newer version of the Contributor Covenant (#14) as 1.4 has been [translated into quite a few languages already](https://www.contributor-covenant.org/translations).

**Comment by mrbobbytables** [comment]
@dankohn Would you mind adding Italian and Ukrainian to the translation request? We have some other folk who have shown interest in those native-language sections as well.

**Comment by dankohn** [comment]
OK.

**Comment by castrojo** [comment]
We've had a request for Korean since the docs are in the process of being translated.

**Comment by mrbobbytables** [comment]
@dankohn I just wanted to touch base, do you happen to have an idea of when the the translations may be available?

**Comment by dankohn** [comment]
Apologies, this should have been done already. Checking.

**Comment by rootsongjc** [comment]
@castrojo Actually Slack is not a tool frequently used in China. Thousands of people ard organized with QQ or WeChat.

**Comment by mrbobbytables** [comment]
Awesome, thanks so much @dankohn !
