### ISSUE TITLE
Take a look at https://www.getro.com to replace the jobs.cncf.io board

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#152]
https://www.getro.com looks like it has more than just a jobs board option, has networking etc

**Comment by westurner** [comment]
Hadn't been aware of https://jobs.cncf.io/ either, thx

**Comment by krook** [comment]
@caniszczyk is this still relevant to explore as an alternative to [ jobs.cncf.io](https://jobs.cncf.io/)?

**Comment by caniszczyk** [comment]
let's close for now
