### ISSUE TITLE
Clarify AGPL3 allowance for member projects

### ISSUE THREAD

**Issue by indrora** [cncf/foundation#158]
Recently, [7 members of the CNCF Landscape](https://landscape.cncf.io/card-mode?grouping=license&license=gnu-affero-general-public-license-v3-0) have decided to move to AGPLv3; most recently [Minio made this change](https://github.com/minio/minio/commit/069432566fcfac1f1053677cc925ddafd750730a) with [confusion about the copyright status of contributions](https://github.com/minio/minio/issues/12155) due to a lack of CLA.

Not only does this cause issues within corporate environments where a strict interpretation of "distribution" (as well as "modification", etc) is used which could result in licensing troubles, the change in license makes it impossible for some enterprises to maintain good security policies [where AGPL3 software is banned](https://opensource.google/docs/using/agpl-policy/)([etc](https://www.skywatertechnology.com/ufaqs/what-are-the-prohibited-licenses/), [etc](https://community.octoprint.org/t/less-restrictive-license/4371/15),)  or [where third parties ban the use of agpl3 software](https://squareup.com/us/en/legal/general/pos), as now those environments are barred from using versions addressing current and as of yet unknown security fixes.

Open source compliance tools such as Sonatype [ban AGPL code by default](https://help.sonatype.com/iqserver/managing/policy-management/license-threat-groups). Additionally, `agpl-recommendations.md` indicates that all source under the CNCF projecst should be Apache2 or in the allowable list of licenses. To the lay reader, the prima facie reading of the charter indicates that projects such as `minio` and `grafana` would fall under the requirements of being in the allowed list of licenses.

So, does AGPL3 have a place on the CNCF Landscape? What of these projects? Are they still part of the landscape?

**Comment by amye** [comment]
This should probably be filed under https://github.com/cncf/landscape/issues instead of /foundation? 
Unless I'm missing the question here, it's directly related to the landscape. 

@indrora, am I correct that you're looking for guidance on the landscape and not the CNCF as a whole?

**Comment by indrora** [comment]
@amye A little of both. I put this here because it's more a meta-question about projects in the CNCF. 

To the lay reader (such as myself) it becomes hard to distinguish "the CNCF Foundation" and members of the CNCF Foundation, the landscape and its constituent projects are held together

If this ticket would be better ported over to `landscape` then I'll close and put it there.

**Comment by indrora** [comment]
Any update on this or should I move it to the `landscape` repo?

**Comment by roidelapluie** [comment]
As far as I know the landscape does not really care about the license. The only question is is it released under an OSI approved license or not. There are also a lot of proprietary tools there.

**Comment by caniszczyk** [comment]
That's correct, everything is welcome on the landscape as long as the new entries terms are met, open source or not: https://github.com/cncf/landscape#new-entries
