### ISSUE TITLE
How to report divergence from CNCF requirements?

### ISSUE THREAD

**Issue by AaronFriel** [cncf/foundation#161]
I cannot find the proper place to submit commentary on a CNCF project, but it may be the the case that a project has in recent months shifted away form meeting the guidelines for CNCF project inclusion.

The [Sandbox Guidelines](https://github.com/cncf/toc/blob/main/process/sandbox.md) require:

> That a project has a legally neutral home that is stable and known
> 
> ...
> 
> 
> A neutral home for your project increases the willingness of developers from other companies and independent developers to collaborate, contribute, and become committers. Neutrality requires that projects contribute their trademark to CNCF so that:
> 
> * No company is favored over any other
> * CNCF ensures project governance is transparent and fair for everyone.

Recent changes to a sandbox project appear to cause it to diverge dramatically from the requirements for incubation stage, and appear to be moving toward the project being a proprietary requiring a third party cloud service and licensing. These changes would appear to preclude it from graduating to the incubation stage.

What is the appropriate venue for concerns such as this?

**Comment by caniszczyk** [comment]
You can shoot me a note @AaronFriel or info@cncf.io

**Comment by caniszczyk** [comment]
Thanks, we connected over email!
