### ISSUE TITLE
License exception for https://crates.io/crates/webpki-roots

### ISSUE THREAD

**Issue by thomastaylor312** [cncf/foundation#172]
https://crates.io/crates/webpki-roots is an MPL-2.0 project that is not currently listed as an exemption. We are asking it be added as an exemption so it can be used as it is a transitive dependency in several major Rust projects. In particular, this was brought up because of its [use in Krustlet](https://github.com/cncf/toc/issues/690#issuecomment-892874955).

Also, with MPL-2.0, is there some sort of requirement to include a NOTICE file or something similar linking to the original code?

**Comment by caniszczyk** [comment]
@amye can you queue this up with swinslow?

**Comment by amye** [comment]
Connecting back in here, we are getting these underway for an April vote! 

Here's the new template that we're working with projects on: 
For all license exception requests, we need the following information in order to help make a decision to grant an exception.
- [] What is the alternative license?
- [] If this is newly created code, why can't it be under Apache-2.0? 
- [] Is this an existing 3rd party open source project?
- [] How does this code integrate with or interact with, if at all, other components of CNCF? 
- [] How will the code be maintained? Who is responsible? 
- [] How will the code be kept up to date with security patches?

**Comment by thomastaylor312** [comment]
**What is the alternative license?**

Not entirely clear on what this means in this context, but there is no "alternative license" for this project. It is only licensed under MPL-2.0

**If this is newly created code, why can't it be under Apache-2.0?/Is this an existing 3rd party open source project?**

N/A. This is an existing 3rd party open source project

**How does this code integrate with or interact with, if at all, other components of CNCF?**

This code is used by Krustlet and is likely to be used by future Rust projects that join the CNCF as webpki-roots is a transitive dependency of various popular crates (pretty much anything that uses `rustls`)

**How will the code be maintained? Who is responsible?/How will the code be kept up to date with security patches?**

Also not sure exactly what information is needed here, but since this is a third party open source project, the maintainers of that project will be responsible for maintenance. However, this library just contains root certificates for various signing authorities. There isn't much code to be maintained

**Comment by amye** [comment]
> **What is the alternative license?**
> 
> Not entirely clear on what this means in this context, but there is no "alternative license" for this project. It is only licensed under MPL-2.0
> 
> **If this is newly created code, why can't it be under Apache-2.0?/Is this an existing 3rd party open source project?**
> 
> N/A. This is an existing 3rd party open source project
> 
> **How does this code integrate with or interact with, if at all, other components of CNCF?**
> 
> This code is used by Krustlet and is likely to be used by future Rust projects that join the CNCF as webpki-roots is a transitive dependency of various popular crates (pretty much anything that uses `rustls`)
> 
> **How will the code be maintained? Who is responsible?/How will the code be kept up to date with security patches?**
> 
> Also not sure exactly what information is needed here, but since this is a third party open source project, the maintainers of that project will be responsible for maintenance. However, this library just contains root certificates for various signing authorities. There isn't much code to be maintained

That's what I needed! 
I realize the questions aren't *as* applicable, but this gets us started. I'll let you know if legal has more questions, but my next steps are 1) drafting this for legal review, 2) they give me the green light, 3)we put this to the GB for review and 4) a vote. 
I will let you know if I have more!

**Comment by amye** [comment]
#568 resolves
