### ISSUE TITLE
Roll out Code of Conduct to CNCF

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#2]
The Hyperledger project recently went through a process to select a code of conduct which will serve as code of conducts for LF collaborative projects moving forward. We will most likely reuse this: https://github.com/hyperledger/hyperledger/wiki/Hyperledger-Project-Code-of-Conduct

**Comment by dankohn** [comment]
Current Kubernetes Code of Conduct: https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md

**Comment by dankohn** [comment]
Conference code of conduct: http://events.linuxfoundation.org/events/linuxcon-north-america/attend/code-of-conduct

**Comment by caniszczyk** [comment]
To @dankohn point, this is across all LF Events for event: http://events.linuxfoundation.org/events/kubecon/attend/code-of-conduct

**Comment by preillyme** [comment]
👍

**Comment by philips** [comment]
One extremely important thing that we MUST include in whatever CoC we adopt: the people responsible for the CoC cannot be hidden behind an email alias and should be explicitly listed. It is unclear from this email address conduct@lists.hyperledger.org if this is publicly archived, where it is archived, and who can read those archives.

I think hyperledger's CoC should be revised as well to fix this. And it should be a blanket policy at the LF.

**Comment by dankohn** [comment]
@philips Presumably you think any email should not be publicly archived. But, any email to me will be archived in my Gmail, and is, therefore subpoenable. Just to be explicit, you're suggesting that:
1. Recipients of the email should be specified, and
2. Email conversations should not be made public.

Anything else?

cc @lehors @mprelude @behlendorf

**Comment by philips** [comment]
Yes, I understand emails are subpoenable. 

Yes, I agree with 1 & 2.

The tone of the hyperledger CoC feels more lawyery than the current one adopted by k8s. Generally you want to avoid that tone when dealing with these topics. But, I don't think that is a blocker.

**Comment by dankohn** [comment]
BTW, I didn't make clear enough that HyperLedger document is almost totally taken from W3C. Adjustments were based on changes from a standards organization to code development.

**Comment by sarahnovotny** [comment]
i'm with @philips on the opinion that these CoCs should be approachable and as un-lawyer-ly as possible.  And that non-specific "report this to a mailing-list" obfuscation decreases trust and accountability which (i postulate) decreases reporting.

**Comment by mprelude** [comment]
@sarahnovotny, what would be your concern with reporting to a mailing list? Lack of anonymity for the reporter or lack of transparency re: who could read it?

What would be your suggestion?

**Comment by sarahnovotny** [comment]
hi @mprelude,  

The answer is a bit of both.  If I've just had a terrible thing happen in relation some person (potentially of power in the community), it's much harder to write to an opaque mailing list than to individuals.  It seems reasonable to fear both who would read the message ("what it goes to the person i'm complaining about?") and if my name is leaked i have not even the recourse of calling out the person(s) i wrote to.  

With specific names (as we use in the [Kubernetes CoC](https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md) (thanks to @philips recommendation) there are options (send mail to Dan or myself or both of us) and direct contacts whose reputation and identities support some escalation path and personal accountability.

**Comment by lehors** [comment]
I understand the concern with using a mailing list. I will bring it up to the Hyperledger TSC for discussion.
Thanks for letting me know.

**Comment by lehors** [comment]
For your information, the Hyperledger CoC has been changed. It now refers to two specific persons to contact in case of incident.
Thanks again for bringing up this issue to my attention.

**Comment by dankohn** [comment]
@lehors I don't see the change on https://github.com/hyperledger/hyperledger/wiki/Hyperledger-Project-Code-of-Conduct

**Comment by caniszczyk** [comment]
This has been officially ratified by the ToC now, so we're all good:
https://lists.cncf.io/pipermail/cncf-toc/2016-November/000452.html

**Comment by mikedanese** [comment]
Sorry about closing this. I think the wording "resolve cncf/foundation#2" in https://github.com/kubernetes/kubernetes/commit/deadea91dc910987b53184aa4b7c8e9b9b8946a8 advises github to close this automatically when the commit entered master.
