### ISSUE TITLE
Update localization with new code of conduct updates

### ISSUE THREAD

**Issue by amye** [cncf/foundation#200]
https://github.com/cncf/foundation/pull/194 will require us to update https://github.com/cncf/foundation/tree/master/code-of-conduct-languages, and there's a lot in here.

Will work with @celestehorgan to reach out to authors for updates.

**Comment by amye** [comment]
@celestehorgan - we can pick this back up again!

**Comment by kumarankit999** [comment]
Why is this issue not closed yet!
