### ISSUE TITLE
Cilium license exceptions required

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#226]
https://github.com/search?p=1&q=org%3Acilium+gpl&type=Code

**Comment by lizrice** [comment]
The FOSSA license scan passes, can we close this? https://app.fossa.com/projects/custom%2B162%2Fgit%40github.com%3Acilium%2Fcilium.git/refs/branch/master/da9d6a0167e1cede54480dbe832ef0ef5dca3aa8

**Comment by lizrice** [comment]
There's a good discussion of why eBPF programs (which are bytecode that runs in the kernel) require GPL-compatible licenses in [this very similar issue](https://github.com/cncf/foundation/issues/474).

 - Cilium's eBPF programs with GPL-compatible licenses are bytecode that runs in the kernel (like any eBPF program) 
 - Cilium's user space components are licensed Apache 2.0, and interact with the kernel using the syscall interface (like any eBPF application)

**Comment by amye** [comment]
This is currently with LF license scanning review.

**Comment by amye** [comment]
Approved by Legal Committee and GB as of a vote for 8-31, minutes will be approved as of the next governing board meeting
