### ISSUE TITLE
Update jobs.cncf.io to have labels for open source work

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#227]
There's been some discussion about having jobs on jobs.cncf.io indicate that a percentage of their time will be spent on developing open source software, including upstream work. I'm thinking of adding labels similar to how jobs describe how much travel would be expected:

* 25% Open Source
* 50% Open Source
* 75% Open Source
* 100% Open Source

Another idea is separating out working on open source projects vs upstream work, and having a separate label to indicate the company gives time for employees to work on upstream.

Thoughts? Also kudos to Paris Pittman for driving some of these ideas at a recent CNCF GB meeting.

**Comment by cjyabraham** [comment]
Note we can make these taxonomy choices "required" so that people have to designate what percent of the job is open source when creating the posting, or we can leave it as optional.

**Comment by puja108** [comment]
Could ranges make sense instead of distinct values? From what I'm seeing at least within our engineers, people with the same role differ in their amount of upstream work, mainly due to personal preference, but sometimes also by the specificity of project they might be currently working on.

**Comment by cjyabraham** [comment]
I momentarily put up a test job posting to test out these new taxonomies.  Here is the job submission screen:
<img width="715" alt="Screen Shot 2021-11-09 at 9 59 39 AM" src="https://user-images.githubusercontent.com/463160/140948378-69e03c5c-7242-4f5e-a153-0885f3e0f30d.png">

How the job looks when posted:
<img width="1136" alt="Screen Shot 2021-11-09 at 10 02 20 AM" src="https://user-images.githubusercontent.com/463160/140948452-eeb188b0-99ed-4224-bb36-593da9003d61.png">

Quick search options.  Note I used the word “Culture” to name the taxonomy with “Upstream Friendly”:
<img width="781" alt="Screen Shot 2021-11-09 at 10 01 54 AM" src="https://user-images.githubusercontent.com/463160/140948521-302ed807-ddbf-4d22-b728-4460dc33aded.png">

After clicking on one of these quick searches you get the results:
<img width="1038" alt="Screen Shot 2021-11-09 at 10 02 13 AM" src="https://user-images.githubusercontent.com/463160/140948606-cfcf6a09-7f7d-419e-bdcb-4848079eae15.png">

**Comment by parispittman** [comment]
Thank you so much!!! This is a great value add to the community. 

For the values for Open Source Time: 25%, 50%, 75%, Other (in job description) would be perfect. 
Folks who select other could be the voices around: "do what you need to do to get the work done", "we're new at this and trying to figure it out but help us?",

**Comment by todaywasawesome** [comment]
Love it, this is great.

**Comment by puja108** [comment]
Thanks so much! This is perfect timing as I was adding more about upstream work to our job descriptions ❤️

**Comment by cjyabraham** [comment]
Hi @parispittman, I don't think what you suggest will work because the tags just appear without context, so if a tag showed up as "Other (see job description)" no one would know that that was referring to open source time.  I think in such a case people could just not choose an open source allocation tag and could describe the situation in the job description?

**Comment by cjyabraham** [comment]
I have deployed the tags live on the site.  Note that descriptions of the tags do show up when people search using one of the tags:
<img width="1302" alt="Screen Shot 2021-11-10 at 9 03 14 PM" src="https://user-images.githubusercontent.com/463160/141127617-ee929ccd-d951-40ea-a71a-706284176b47.png">
<img width="1326" alt="Screen Shot 2021-11-10 at 9 03 45 PM" src="https://user-images.githubusercontent.com/463160/141127639-21a8cdf5-4f32-4877-9fa3-7517573b5d1a.png">

**Comment by cjyabraham** [comment]
We've changed "Upstream Friendly" to have a higher bar of entry by calling it "Upstream Commitment".

**Comment by caniszczyk** [comment]
Thanks @cjyabraham, can we ensure the descriptions are updated for these things in https://jobs.cncf.io/about and that anyone that has an Upstream Commitment gets a free featured job marker.

**Comment by cjyabraham** [comment]
I have added an FAQ on [the About page](https://jobs.cncf.io/about) to define the tags.  I have also asked @libbyschulze to promote jobs marked "Upstream Commitment".

**Comment by caniszczyk** [comment]
thanks :)
