### ISSUE TITLE
Code of Conduct spelling mistake

### ISSUE THREAD

**Issue by Rossiar** [cncf/foundation#254]
There is a minor spelling mistake in the code of conduct on [this line](https://github.com/cncf/foundation/commit/d6ac18a62211414a29d17d640717e9925f71d534#diff-f1a69a41a835b5265e1c58e11395a894ac30fc6b0afe1ca834738955261d2ec5R40) where 
`iconjunction` should read `in conjunction`

**Comment by Noel-Dason** [comment]
I am really new to open source and would like to contribute by fixing this issue, could you please tell me how I should go forward with this?

**Comment by amye** [comment]
New CoC resolves!
