### ISSUE TITLE
CLAbot is lacking logs 

### ISSUE THREAD

**Issue by dims** [cncf/foundation#26]
This is especially painful when doing git surgery, examples
- filtering some files in git (examples in https://github.com/kubernetes/utils/pulls)
- moving stuff between branches (example https://github.com/kubernetes/kubernetes/pull/73042)
- between repos ( https://github.com/kubernetes-csi/csi-driver-host-path/pull/1 )

Let's take an example - https://github.com/kubernetes/utils/pull/55, the bot says:
`cla/linuxfoundation — dims authorized, but 1 other problem`

and the `Details` link points to `https://identity.linuxfoundation.org/projects/cncf` which is not helpful as we should not be pinging the helpdesk to figure out which git commit in a PR is causing an issue.

Can we please do better? 
- log exactly why the bot thinks the PR is bad
- link to logs, so we can go look at the verbose output from the bot

**Comment by dims** [comment]
kind of related to https://github.com/cncf/foundation/issues/3

**Comment by dims** [comment]
currently the only way in k/k repos is to run the prow `/override` command by an admin to clear the bot status (tip courtesy of @bentheelder)

**Comment by idvoretskyi** [comment]
cc @caniszczyk @idvoretskyi

**Comment by dankohn** [comment]
@dims We are ready to replace the old CLAbot with a newly developed one. One of the big strengths is that it will be open source. So, while I'm sure it will have some new (and different bugs), it should be feasible to resolve them much faster.

I had some hesitation on rolling out to Kubernetes first, and was hoping to use gRPC as our beta tester. If you feel differently, we could swap that around. Either way, we would love your help if you would be willing to take a look at what we have built.

Cc @ShubhraKar

**Comment by ShubhraKar** [comment]
@dims please let me know if you want to preview the new CLA tool. Happy to share.

**Comment by dims** [comment]
@ShubhraKar sure! yes please

**Comment by ShubhraKar** [comment]
Could you please provide your email or send me a note on skar@linuxfoundation.org so that I can schedule a meeting? Anyone else we should be inviting to the preview @dims @dankohn ?

**Comment by thisisnotapril** [comment]
@dankohn FWIW, gRPC would be happy to be the beta tester as well!

**Comment by dankohn** [comment]
That's great to hear, @thisisnotapril. We'd like to provide a demo for you as well. We don't want to switch over until you say it's ready, but gRPC is lower volume and so would make sense to start with.

**Comment by jpalmerLinuxFoundation** [comment]
@dims I shared some quick mockups for you regarding the logs. Just want to get some feedback going so I can understand the need better: https://github.com/communitybridge/easycla/issues/169

**Comment by caniszczyk** [comment]
all issues should go to https://github.com/communitybridge/easycla

**Comment by dims** [comment]
This is still not fixed for kubernetes ... https://github.com/kubernetes/kubernetes/pull/98735#issuecomment-772776508

@caniszczyk can you please reopen this?

**Comment by caniszczyk** [comment]
@dims leaving this closed and instead opening the issue here for you https://github.com/communitybridge/easycla/issues/2664

EasyCLA team will take it over, less a CNCF thing and more an EasyCLA issue

**Comment by dims** [comment]
@caniszczyk thanks!
