### ISSUE TITLE
Transitioning Knative into CNCF

### ISSUE THREAD

**Issue by amye** [cncf/foundation#317]
This one has a few moving parts, so I want to make sure we're tracking various workstreams here.

Full agreements from: 
- [x] Google
- [x] Red Hat
- [x] VMWare

Specific streams: GCP is currently tracking here, more to be added as needed. 
GCP: 

- [x] Domain name
- [ ] Account created by LFIT
- [ ] Credit transfer

**Comment by amye** [comment]
Marking Google complete.

**Comment by taniaduggal** [comment]
Hey @amye .I wanna work on this issue . How can I get started ? Could you guide me please.
