### ISSUE TITLE
License exception for ory/dockertest

### ISSUE THREAD

**Issue by jon-whit** [cncf/foundation#346]
Various Go projects use the `github.com/ory/dockertest` package to assist in the development of tests (unit and functional) that run against a real database. It's a wrapper around `github.com/fsouza/go-dockerclient` that makes management of container spin up/down for tests easier.

Docker explicitly references usage of and recommends usage of `github.com/ory/dockertest` for Go testing with container driven test setup. As such, I have seen a lot of usage of it in various Go communities.
https://docs.docker.com/language/golang/run-tests/

Would your governing body consider adding it to the exception list, since it's essentially just a wrapper around a pre-approved docker client?

**Comment by amye** [comment]
Question here: is this coming from a particular project?

**Comment by dims** [comment]
@jon-whit As amye implied, the exception request should be associated with a current CNCF project. If you are enquiring about openfga? we (CNCF TOC) needs to work on the sandbox submission first (and accept) before the GB can deal with the exception request.

**Comment by jon-whit** [comment]
> openfga? we (CNCF TOC) needs to work on the sandbox submission first (and accept) before the GB can deal with the exception request.

Sounds good 👍 . Thanks for the info @amye and @dims !
