### ISSUE TITLE
License exception for `github.com/docker/docker/client`

### ISSUE THREAD

**Issue by jon-whit** [cncf/foundation#347]
I noticed that the `github.com/fsouza/go-dockerclient` Go package is on the exception list, but the official `github.com/docker/docker/client` is not. The `github.com/fsouza/go-dockerclient` even recommends any new projects should use the official Docker client SDK from Docker.

Would your governing body consider an exception for `github.com/docker/docker/client` (as the fsouza package recommends) or is there a strong reason that the governing body only supports the existing one on the exception list?

**Comment by dims** [comment]
@jon-whit the docker/docker/client is under Apache License 2.0 it does not need an exception, we use this in cadvisor and containerd etc (see their go.mod's)
