### ISSUE TITLE
Be able to list CNCF new CNCF projects in order of acceptance

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#348]
We had complaints from folks that it's hard to keep up to date with projects.

We should the ability to generate info for each:
- who is involved
- what's new in terms of features

Let's experiment for kubecon detroit

**Comment by dims** [comment]
good point. perhaps links to the roster and changelog+blog-for-latest-release?

**Comment by parispittman** [comment]
this crosses into this a little bit: https://github.com/cncf/enduser-public/issues/37

it's really hard to keep track of things as an end user for 100+ projects, especially at orgs that are using 30+ of them.

**Comment by caniszczyk** [comment]
this is done now as CNCF has metadata in it for project acceptance date, you can download the CSV from the landscape and get this info for your hearts content
