### ISSUE TITLE
When we fork an Apache License 2.0 project that we depend on, are there any restrictions on the name/path for imports

### ISSUE THREAD

**Issue by dims** [cncf/foundation#354]
Context: please see discussion in https://github.com/kubernetes-sigs/yaml/pull/76#issuecomment-1137770406

cc @mkdolan

**Comment by caniszczyk** [comment]
In short, no restrictions on name/path for imports, you just have to preserve any copyright information in the files (along with any usual attributions)

**Comment by dims** [comment]
thanks @caniszczyk !!! wanted this on the record :)

**Comment by dims** [comment]
related to https://github.com/cncf/toc/issues/877
