### ISSUE TITLE
RFC: Code of Conduct should be requirement for all CNCF projects

### ISSUE THREAD

**Issue by lizrice** [cncf/foundation#36]
According to [this criteria doc](https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc), the CNCF code of conduct appears to be required only at Graduation. Is there any reason not to require this of all projects, including Sandbox and Incubation?

**Comment by dankohn** [comment]
I think the CoC was seen as more controversial 2 years ago where now it's understood as simply good practice. I would support requiring it for all projects.

**Comment by caniszczyk** [comment]
ya I put it here for a clarification:

https://github.com/cncf/toc/pull/227

**Comment by ultrasaurus** [comment]
FYI: there may be reasons that it could take some time to work through adopting the CNCF CoC specifically, if the project already has a different code of conduct.  

Consider:
- all projects must have CNCF code of conduct or approved equivalent.  
- sandbox/incuabating projects must have a CoC, graduated projects must have CNCF code of conduct

**Comment by lizrice** [comment]
This is a very valid point, but it would be nice to get all projects consistent. If an incoming project already has an equivalent CoC then it's a trivial change to adopt the CNCF one; if they believe they would be losing something important then that might indicate we should be considering an update to the CNCF one

**Comment by cblecker** [comment]
Any update on this?

**Comment by krook** [comment]
The CNCF CoC is required at all maturity levels:

https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/project-onboarding.md
https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-incubation-application.md#required-1
https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-graduation-application.md#required-1
