### ISSUE TITLE
Consider adding OFL-1.1 variants to the allow list

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#360]
https://opensource.org/licenses/OFL-1.1

https://github.com/prometheus/prometheus/issues/10767

**Comment by davegandy** [comment]
Creator of Font Awesome here. We've tried to make the license as open as we possibly can. Happy to answer any questions needed to help folks get this sorted.

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by amye** [comment]
A blanket exception to allow use of any Fontawesome font licensed under the SIL Open Font License 1.1 ([OFL-1.1](https://spdx.org/licenses/OFL-1.1.html))was approved by Legal Committee and GB as of a vote for 8-31, minutes will be approved as of the next governing board meeting.
