### ISSUE TITLE
add minikube maintainers

### ISSUE THREAD

**Issue by medyagh** [cncf/foundation#399]
Hi we (minikube mainainers) would like to be added to the list of maintainers in 
https://github.com/cncf/foundation/blob/main/project-maintainers.csv

what is right way of doing it ?

**Comment by amye** [comment]
No, subprojects of Kubernetes are not listed here.

**Comment by medyagh** [comment]
@amye thanks for the clarifying, I need to create a ticket for user metrics in help desk, but we dont have an account to create a support ticket, do you have any suggestions how we could do that?

**Comment by parispittman** [comment]
@medyagh reach out to the steering committee to help
