### ISSUE TITLE
iCLA should have explanation of why we need it

### ISSUE THREAD

**Issue by foxish** [cncf/foundation#4]
For the corporate CLA signers, the organizations/lawyers verify the terms of the CLA. For an individual looking to sign it, it may appear daunting. Perhaps we should have a landing page as the first step which explains the need for a CLA, so as to not startle someone with several pages of intimidating legalese right away

**Comment by foxish** [comment]
cc @bgrant0607

**Comment by krook** [comment]
Each individual project has contribution guidelines that outline whether they use the DCO or CLA and why, in addition to the [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).

For example, [Kubernetes explains their CLA here](https://kubernetes.io/docs/contribute/new-content/#sign-the-cla) and [here](https://github.com/kubernetes/community/blob/master/CLA.md).

If this is still a need though, feel free to re-open the issue.
