### ISSUE TITLE
License exception request: additional hashicorp packages used by Cilium project

### ISSUE THREAD

**Issue by lizrice** [cncf/foundation#400]
We would like to request license exceptions for the following Go packages that Cilium uses, that are licensed under MPL-2.0.  
 - github.com/hashicorp/consul/api
 - github.com/hashicorp/serf
 - github.com/hashicorp/go-rootcerts
 - github.com/hashicorp/go-immutable-radix
 - github.com/hashicorp/go-hclog
 
FOSSA also flags up the following packages that Cilium is using, but that are already included in the list of [GB-approved exceptions](https://github.com/cncf/foundation/tree/main/license-exceptions): 
 - github.com/hashicorp/go-cleanhttp
 - github.com/hashicorp/hcl
 - github.com/hashicorp/golang-lru
 
(For some reason go-hclog was not actually flagged up in the Cilium FOSSA scan, but it also uses MPL-2.0 so we are assuming we would also need an exception for that one.)

**Comment by joamaki** [comment]
I would like to add github.com/hashicorp/go-memdb to the list of requested exceptions. PR adding it to Cilium: https://github.com/cilium/cilium/pull/24523.

**Comment by lizrice** [comment]
Publicly documenting some follow-up Q&A from an email thread on the Cilium maintainers list: 

> From: Amye Scavarda Perrin <ascavarda@linuxfoundation.org>
> Date: Tue, May 16, 2023 at 9:01 PM
> Subject: Re: [cncf-cilium-maintainers] Licensing Exception Request for Cilium
> To: <cncf-cilium-maintainers@lists.cncf.io>
> 
> 
> Thank you so much for the quick response! 
> I'm working to collate the outstanding requests for a June 8th meeting, this issue is prioritized for that meeting.
> 
>

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by richardfontana** [comment]
https://pkg.go.dev/github.com/hashicorp/go-hclog and the GitHub licensee display at https://github.com/hashicorp/go-hclog suggest the license is MIT rather than MPL-2.0 - is that not accurate?

**Comment by dims** [comment]
@richardfontana you are right `hashicorp/go-hclog` has always been MIT looking at [LICENSE](https://github.com/hashicorp/go-hclog/blob/main/LICENSE) and [first commit of LICENSE](https://github.com/hashicorp/go-hclog/commit/9eff3a55e17232000294a1708b2f27322851a404). So that should be good.

**Comment by amye** [comment]
This was approved on 6-27 by the Governing Board. #589 resolves.
