### ISSUE TITLE
Disappeared from maintainers list

### ISSUE THREAD

**Issue by Jarema** [cncf/foundation#402]
I found out by accident, that I'm no longer on maintainers list, despite not seeing (or missing) any relevant commit.

I was added here: https://github.com/cncf/foundation/pull/371

and bisect lead me to "first bad commit" `99f6eb0c55b74f42f52fefd5b2d0851ca192e51b` which does not make much sense, unless there were some mistakes in rebases/merges.

Created an issue, as it might have affected others too.

**Comment by amye** [comment]
Good news, it was just an error and you're still on the maintainers list. I've put you back. :)
