### ISSUE TITLE
dco-guidelines.md: disallow/allow using `@users.noreply.github.com` email addresses

### ISSUE THREAD

**Issue by AkihiroSuda** [cncf/foundation#407]
https://github.com/cncf/foundation/blob/e0060f51/dco-guidelines.md

> The key concern is that your identification is sufficient enough to contact you if an issue were to arise in the future about your contribution.

For this concern, the DCO guidelines should explicitly disallow using `@users.noreply.github.com` email addresses?

**Comment by dims** [comment]
@AkihiroSuda i have a feeling that as someone's github profile is still unique and folks can be reached by `@` addressing them on issues and PRs to get their attention. So i think that passes the test.

However if someone is using a fake / non-existent github profile handle in their email, that would not pass the test.

Note that there is a general problem .. we don't have a way to "verify" (as say a github action) to ensure the policy in the guidelines doc are enforced. This is left to projects to watch out for incoming contributions ...

**Comment by AkihiroSuda** [comment]
>  i have a feeling that as someone's github profile is still unique and folks can be reached by @ addressing them on issues and PRs to get their attention. 

Usually yes, but the person may remove the GitHub account, lose access to the account, or get banned in a bad situation.

**Comment by dims** [comment]
@AkihiroSuda for sure... also can you please read through the background discussion https://github.com/cncf/foundation/issues/383#issuecomment-1178254458 to get a sense of why the policy is set this way. thanks!

**Comment by AkihiroSuda** [comment]
Thanks
