### ISSUE TITLE
CNCF Projects using Akka are at risk as their LICENSE has changed to BSL 1.1

### ISSUE THREAD

**Issue by dims** [cncf/foundation#416]
We need to check if any of our projects use Akka and figure out how to transition/sunset the support or usage of Akka

- https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
- https://www.lightbend.com/akka/license-faq

Also see https://issues.apache.org/jira/browse/LEGAL-620 and https://flink.apache.org/news/2022/09/08/akka-license-change.html

**Comment by dims** [comment]
otel-java seems to be using Akka https://github.com/open-telemetry/opentelemetry-java-instrumentation/search?q=akka

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by amye** [comment]
https://github.com/cncf/foundation/blob/main/source-available-recommendations.md has been published. @dims - do we need more on this?

**Comment by dims** [comment]
@amye all good Amye. we can close this now. thanks!
