### ISSUE TITLE
[Question] Cloud native definition

### ISSUE THREAD

**Issue by ehhc** [cncf/foundation#42]
Hi,
i have a question and hope, this is the right place to answer it. A lot of definitions about what cloud native applications state that they are characterized by the three points below:
```
- Containerized: Each part (applications, processes, etc) is packaged in its own container. This facilitates reproducibility, transparency, and resource isolation.
- Dynamically orchestrated: Containers are actively scheduled and managed to optimize resource utilization.
- Microservices oriented: Applications are segmented into microservices. This significantly increases the overall agility and maintainability of applications
```

Often you are given as the source of this definition. I think it's nice because it defines three distinct points i can use to discuss with others when talking about cloud native.

Unfortunately, in revision 7 of your charter (https://github.com/cncf/foundation/commit/a121a45bf62dccb8ed8b2d832c41bc43cfb20c0c) you replaced this explicit definition through a more generic one, deleting this explicit three-point definition.

May i ask why you decided to change the definition this way?

Best regards

**Comment by dankohn** [comment]
Good job uncovering the history. Those three points were included in the original version of the charter, but the TOC felt that they were not fully representative of cloud native. @bgrant0607 led an effort to define the Cloud Native Definition, which was first adopted unanimously by the TOC and then unaninmously incorporated into the charter by the governing board.

I mention the evolution of the definition in my 11 minute Barcelona keynote: https://www.youtube.com/watch?v=lmGFgZ889kY

Feel free to keep using the 3 points if you want, but note that it's not fully representative of all parts of cloud native. In particular, it misses a focus on observability and declarative APIs.

I'm closing but feel free to continue the conversation here.

**Comment by ehhc** [comment]
Wow. first of all, thanks for your quick reply. 
I'll watch your keynote. 
Maybe i'll come back later if i have further questions, if that's okay with you.

Thanks for the explanation again... :)
