### ISSUE TITLE
[Question] Is Microservice mandatory for cloud native ? 

### ISSUE THREAD

**Issue by iasna** [cncf/foundation#429]
I have a question, I have been looking into articles, books and videos regarding cloud native.  CNCF official definition of cloud-native says the application should be microservice. What I'm confused about is an application being a microservice to called cloud-native. What if I have an application that is not microservice but broken into smaller independently scalable & resilient component that is able to harness the power of the cloud using containers and orchestration tools like openshift, Kubernetes. The services are observable and communicate with each other using a broker. The reason why it is not microservices is that they share the same data store & repository, but the DevOps pipeline creates a separate image for every service. I was going through https://www.youtube.com/watch?v=d_8Vly4_ofo
In this video of yours where a presentator to one of the questions answered that microservice is one of the aspects, application can be cloud native without being microservice & vice-versa. So, If I'm not completely microservice can I call myself cloud-native.

**Comment by caniszczyk** [comment]
Just because you are a microservice, doesn't necessarily mean you are cloud native, you exhibit one of the attributes of cloud native architectures. The Cloud Native definition covers this: https://github.com/cncf/toc/blob/main/DEFINITION.md

> Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. Containers, service meshes, microservices, immutable infrastructure, and declarative APIs exemplify this approach.
> 
> These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust automation, they allow engineers to make high-impact changes frequently and predictably with minimal toil.
> 
> The Cloud Native Computing Foundation seeks to drive adoption of this paradigm by fostering and sustaining an ecosystem of open source, vendor-neutral projects. We democratize state-of-the-art patterns to make these innovations accessible for everyone.

**Comment by iasna** [comment]
Yes, I understand that. If I'm not microservice but miniservice instead and also cover other attributes of cloud-native apps, can I call myself cloud-native.
