### ISSUE TITLE
License exception request: k6-operator usage on Dapr project for e2e stress tests

### ISSUE THREAD

**Issue by mcandeia** [cncf/foundation#461]
We would like to request a license exception for the [k6](https://github.com/grafana/k6) AGPL-3.0 to be used on [Dapr Project](https://github.com/dapr/dapr) via [k6-operator](https://github.com/grafana/k6-operator) Apache-2.0.

**What is the alternative license?**
None, as they are single license

**If this is newly created code, why can't it be under Apache-2.0?**
It is not newly created code. > 6 years old.

**Is this an existing 3rd party open source project?**
Yes

**How does this code integrate with or interact with, if at all, other components of CNCF?**
Used only for testing purposes. In this case, e2e stress tests.

**How will the code be maintained? Who is responsible?**
The authors (Grafana Labs).

**How will the code be kept up to date with security patches?**
The authors (Grafana Labs).

I guess this request is pretty much one of the bullet points mentioned in the [AGPL recommendations](https://github.com/cncf/foundation/blob/main/agpl-recommendations.md#seek-an-exception-from-the-governing-board), since the k6-operator is under Apache-2.0, correct me if I'm wrong.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/5839364/203334417-39aa433a-9063-46df-b17e-a74407b3a0c1.png">

**Comment by berndverst** [comment]
The other question is - do we need to actually file this request given that `k6-operator` does not end up in our binaries / artifacts we distribute?

**Comment by amye** [comment]
> The other question is - do we need to actually file this request given that `k6-operator` does not end up in our binaries / artifacts we distribute?

This is actually something that I think I'd like a little more clarity on -  (1) Is this used only for testing purposes and (2)  It's not combined with any other CNCF project?

**Comment by amye** [comment]
@mcandeia - ping on this?

**Comment by yaron2** [comment]
> > The other question is - do we need to actually file this request given that `k6-operator` does not end up in our binaries / artifacts we distribute?
> 
> This is actually something that I think I'd like a little more clarity on - (1) Is this used only for testing purposes and (2) It's not combined with any other CNCF project?

Dapr maintainer here - this is only used for testing purposes and does not getting shipped as part of the binaries that end users use. It is not combined with any other CNCF project other then the fact it is run on a K8s cluster that is used for our performance tests.

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by howardjohn** [comment]
Was there an outcome from the committee? We are interested in similar testing usage

**Comment by amye** [comment]
Not yet! When an outcome is available, I'll post it here.

**Comment by amye** [comment]
Approved by Legal Committee and GB as of a vote for 8-31, minutes will be approved as of the next governing board meeting
