### ISSUE TITLE
adding minikube and minikube-guil to maintainers.csv

### ISSUE THREAD

**Issue by medyagh** [cncf/foundation#470]
Hello I would like to add maintainers for  https://github.com/kubernetes-sigs/minikube-gui and https://github.com/kubernetes/minikube to the maintainers list here 
https://github.com/cncf/foundation/blob/main/project-maintainers.csv

What is the process for that ? do we just create a PR for it ?

**Comment by mrbobbytables** [comment]
Kubernetes steering represents all kubernetes projects in the maintainer list. No subprojects or other things can be listed.
