### ISSUE TITLE
License exception for external-secrets (hashicorp)

### ISSUE THREAD

**Issue by moolen** [cncf/foundation#485]
Hey, we would like to request license exceptions for the following Go packages. We have a similar situation like cert-manager in https://github.com/cncf/foundation/issues/381.

| Project  | License  |
|---|---|
| https://github.com/hashicorp/go-immutable-radix  | MPL-2.0 |
| https://github.com/hashicorp/go-retryablehttp  | MPL-2.0   |
| https://github.com/hashicorp/go-plugin  | MPL-2.0 |
| https://github.com/hashicorp/go-rootcerts  | MPL-2.0 |
| https://github.com/hashicorp/go-secure-stdlib  | MPL-2.0  |
| https://github.com/hashicorp/go-sockaddr  | MPL-2.0 |
| https://github.com/hashicorp/go-uuid  | MPL-2.0  |
| https://github.com/hashicorp/vault  | MPL-2.0  |
| https://github.com/hashicorp/go-version  | MPL-2.0|
| https://github.com/hashicorp/yamux  | MPL-2.0 |

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by amye** [comment]
This was approved on 6-27 by the Governing Board. #589 resolves.
