### ISSUE TITLE
Where to submit security vulnerabilities for cncf projects?

### ISSUE THREAD

**Issue by pierreozoux** [cncf/foundation#5]
For instance there is this issue:
https://github.com/kubernetes/charts/issues/391

I don't know if it is serious or not, but I believe that if it is a serious one, it shouldn't be public.
This should be sent to a an email and addressed outside of public discussions.

For instance:
https://www.chromium.org/Home/chromium-security/reporting-security-bugs

Once there is such a procedure, would be nice if there is a line on each README of each project, and maybe the bot could read issues, and if sees "security" keyword, then delete it, and send emails. Just an idea.

**Comment by caniszczyk** [comment]
This is decided on a per project basis. For k8s, check out this issue:
https://github.com/kubernetes/community/pull/126
