### ISSUE TITLE
License exception for Windows Exporter

### ISSUE THREAD

**Issue by roidelapluie** [cncf/foundation#514]
This is a request an exception to the CNCF licensing requirements to move the [Windows Exporter](https://github.com/prometheus-community/windows_exporter) project within the graduated Prometheus project and organization, as outlined in the CNCF charter (https://github.com/cncf/foundation/blob/main/charter.md). The Windows Exporter is currently released under the MIT license, but the CNCF mandates that all projects must be released under the Apache-2 license.

I believe that granting an exception for the Windows Exporter would be beneficial for several reasons:

- The Windows Exporter is a valuable addition to the Prometheus project, and allowing it to be included in the CNCF would provide additional benefits to the community.
- The MIT license is a permissive and open source license that allows for broad use and distribution of the software. 

There are currently 98 identified contributors to the Windows Exporter project, and it would be extremely difficult and time-consuming to contact and obtain permission from all of them to switch to the Apache-2 license.

Note that the Windows Exporter is an optional addon to Prometheus, and is not required for the core monitoring and alerting functionality of the product.

I hope that the Governing Board will consider granting an exception to the licensing requirements for the Windows Exporter within the graduated Prometheus project.

**Comment by amye** [comment]
This is currently scheduled for review in the June 8th meeting of the Legal Committee.

**Comment by roidelapluie** [comment]
> This is currently scheduled for review in the June 8th meeting of the Legal Committee.

Any news here?

**Comment by amye** [comment]
This was approved on 6-27 by the Governing Board.
