### ISSUE TITLE
The Azure Service Bus metric reports wrong count of Messages in the Queue

### ISSUE THREAD

**Issue by eugen-nw** [cncf/foundation#557]
I'm running `kubectl describe hpa` to see how thing go.  Sometime it reports 0 Messages, which appears to cause the scale-out to not get activated.  Sometimes it reports astronomical figures like the one below:

![image](https://user-images.githubusercontent.com/15199814/235756429-e20fe1cc-848b-42ce-8c22-615c5e392a38.png)

**Comment by amye** [comment]
This probably shouldn't go here?

**Comment by eugen-nw** [comment]
And where it should go please?  Isn't KEDA who's installing the metric?

FYI, I've installed the "keda-2.10.2" chart.

**Comment by amye** [comment]
This repository is for overall foundational issues, usually changes in maintainer lists. 
You might try https://github.com/kedacore/keda/
