### ISSUE TITLE
Update code-of-conduct.md for Hindi

### ISSUE THREAD

**Issue by kumarankit999** [cncf/foundation#602]
Why this term needs to be updated? (briefly)
Localize Code of Conduct for Traditional Hindi because it is available in various languages excluding Hindi.
-  https://github.com/cncf/foundation/blob/main/code-of-conduct.md

**Comment by anubha-v-ardhan** [comment]
Thank you for the issue @kumarankit999. I'll localize it.

**Comment by kumarankit999** [comment]
No, Man  @anubha-v-ardhan I want to work on this issue

**Comment by anubha-v-ardhan** [comment]
@kumarankit999, Just noticed it's also outdated and not just a link issue. You can update it and open a PR.

**Comment by kumarankit999** [comment]
OK, that will be great @anubha-v-ardhan

**Comment by kumarankit999** [comment]
Now the issue looks good @anubha-v-ardhan

**Comment by kumarankit999** [comment]
Now the issue looks good. Can you tell me the Installation process of this repo @anubha-v-ardhan

**Comment by kumarankit999** [comment]
Hey @caniszczyk, but it is not linked yet. Can you see the above PR of @anubha-v-ardhan
