### ISSUE TITLE
Code of Conduct Updates to remove mediator from translations

### ISSUE THREAD

**Issue by geekygirldawn** [cncf/foundation#609]
While the main code of conduct has been changed to remove Mishi as the mediator contact and replace them with the new code of conduct email, it looks like the translations have not been updated. Here is an example: https://github.com/cncf/foundation/blob/main/code-of-conduct-languages/es.md

I'm not sure who handles translations, but hopefully someone can tackle this when they have the time.

**Comment by CFly17** [comment]
Hey there @geekygirldawn, I speak Spanish and am happy to help. Is there something I can do to contribute here?

**Comment by geekygirldawn** [comment]
Honestly, I'm not sure. I just noticed the issue, but I don't do any work in this area at all. Maybe @amye or @caniszczyk would know?

**Comment by rarjun7777** [comment]
@amye @caniszczyk  can i work on this issue ?

**Comment by amye** [comment]
I'm actually going to close this because it applies more broadly - all of the code of conduct translations need to be updated to current version. New issue coming shortly!
