### ISSUE TITLE
Twitter X Logo

### ISSUE THREAD

**Issue by malaviya-parth** [cncf/foundation#618]
In the footer change the twitter logo to new twitterX logo
![image](https://github.com/cncf/foundation/assets/82119640/e85a6adf-7cb3-4293-9ea2-2769de924f4a)

**Comment by jeefy** [comment]
Heya! Please open this in the https://github.com/cncf/cncf.io repo. :) Thanks!

**Comment by malaviya-parth** [comment]
Sure
