### ISSUE TITLE
License exception for Terraform Provider SDK

### ISSUE THREAD

**Issue by stefanprodan** [cncf/foundation#619]
Any CNCF project that offers a Terraform Provider for installation purposes imports the following Hashicorp Go packages (MPL 2.0):

```
github.com/hashicorp/terraform-plugin-docs
github.com/hashicorp/terraform-plugin-framework
github.com/hashicorp/terraform-plugin-framework-timeouts
github.com/hashicorp/terraform-plugin-framework-validators
github.com/hashicorp/terraform-plugin-go
github.com/hashicorp/terraform-plugin-log
github.com/hashicorp/terraform-plugin-sdk
github.com/hashicorp/terraform-plugin-testing
```

For the Flux project we offer such a provider here https://github.com/fluxcd/terraform-provider-flux.
[Harbor](https://github.com/goharbor/terraform-provider-harbor), [AthenZ](https://github.com/AthenZ/terraform-provider-athenz) and potentially many more CNCF projects maintain such providers.

Given that several Hashicorp Go packages are already in the CNCF [exceptions list](https://github.com/cncf/foundation/tree/main/license-exceptions), I propose we add the Terraform Provider SDK ones as well.

xref:
- https://github.com/cncf/foundation/issues/617
- https://github.com/fluxcd/flux2/issues/4156

**Comment by imjasonh** [comment]
https://github.com/ko-build/terraform-provider-ko

**Comment by krook** [comment]
On March 21, 2024, the Governing Board approved an exception to allow CNCF projects to use these dependencies under MPL-2.0, so long as they are used in unmodified form by linking to the dependency at build time.

**Comment by stefanprodan** [comment]
Great news, thanks @krook
