### ISSUE TITLE
[License Exception Request] For common C/C++ libraries: libcurl, libelf, uthash

### ISSUE THREAD

**Issue by leogr** [cncf/foundation#629]
The C/C++ libraries (`libcurl`, `libefl`, `uthash`) for which this issue requests license exceptions to be approved are commonly utilized across various CNCF projects. These dependencies are typically vital for these projects, given the absence of any compelling alternatives in C/C++.

- `libcurl`
    -  The underlying library that powers [curl](https://curl.se/), provides projects with functions to handle data transfers and interact with different internet protocols programmatically. It's widely used and hard to replace. The _curl License_ is inspired by [MIT/X](https://spdx.org/licenses/X11.html), but not identical.
    - **URL**: https://github.com/curl/curl
    - **License**: [curl License](https://spdx.org/licenses/curl.html)
    - **Used by**:
        - [Envoy](https://github.com/search?q=org%3Aenvoyproxy+libcurl&type=code)
        - [Falco](https://github.com/falcosecurity/libs/blob/master/cmake/modules/curl.cmake)
        - [Istio](https://github.com/search?q=org%3Aistio+libcurl&type=code)
        - [KubeVirt](https://github.com/search?q=org%3Akubevirt+libcurl&type=code)
        - [Longhorn](https://github.com/search?q=org%3Alonghorn+libcurl&type=code)
        - [OPA](https://github.com/open-policy-agent/contrib/blob/main/pam_opa/pam/http.c#L4)
        - [OpenCurve](https://github.com/search?q=org%3Aopencurve+libcurl&type=code)
        - [Rook](https://github.com/search?q=org%3Arook+curl.h&type=code)
- `libelf`
    - A library for handling, analyzing, and generating files in the ELF (Executable and Linkable Format). Projects use `libelf` to read, modify, or create ELF files within their software projects, which is usually particularly relevant when dealing with eBPF-compiled programs. It's widely used and part of most Linux distributions. Many libraries and tools depend on `libelf,` which is basically not replaceable with another library. When using `libelf` unmodified, projects can opt for LGPLv3 (which is more permissive than GPLv2), and this allows linking to the library without requiring the rest of the program to be LGPL-licensed. Note that `libelf` is developed as a component of _elfutils_, which includes various other libraries and utilities. However, this request specifically concerns `libelf` and does not extend to other software within the _elfutils_ umbrella.
    - **URL**: https://sourceware.org/elfutils/
    - **License**: (dual) [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html) _or_ [LGPL-3.0-or-later](https://spdx.org/licenses/LGPL-3.0-or-later.html)
    - **Used by**:
        - [Falco](https://github.com/falcosecurity/libs/blob/master/cmake/modules/libelf.cmake)
        - [Inspektor Gadget](https://github.com/search?q=repo%3Ainspektor-gadget%2Finspektor-gadget%20libelf&type=code)
        - [KubeVirt](https://github.com/search?q=org%3Akubevirt+libelf&type=code)
        - [Minikube](https://github.com/search?q=org%3Akubernetes+libelf&type=code) (?)
        - [Pixie](https://github.com/search?q=repo%3Apixie-io%2Fpixie%20libelf&type=code)
        - [Tetragon](https://github.com/search?q=repo%3Acilium%2Ftetragon%20libelf&type=code)
        - [WasmEdge](https://github.com/search?q=org%3AWasmEdge+libelf&type=code)
- `uthash`
    - A lightweight, portable macro-based C library for adding hash tables to your C programs. It enables projects to easily manage hash tables without external dependencies, using simple-to-follow macros integrated directly into their source code. It is licensed under BSD-1-Clause, which is very permissive (and similar to BSD-2-Clause and BSD-3-Clause that are already in the Allowlist).
    - **URL**: https://github.com/troydhanson/uthash
    - **License**: [BSD-1-Clause](https://spdx.org/licenses/BSD-1-Clause.html)
    - **Used by**:
        - [Falco](https://github.com/falcosecurity/libs/blob/master/cmake/modules/uthash.cmake)
        - [WasmEdge](https://github.com/search?q=org%3AWasmEdge%20uthash&type=code)

The list of projects using them is not exhaustive. Additionally, inspired by [this template](https://github.com/cncf/foundation/pull/313), below is some helpful information.

- **If it is Apache-2.0 for code or CC-BY-4.0 for documentation, no further exception request is required**.
    - *No, they are not Apache-2.0 or CC-BY-4*.
- **Do they meet the Allowlist policy? If so, no further exception request is required**.
    - *These depedencies do not meet the Allowlist policy*.
- **Will the code be used in modified or unmodified form**? 
    - *These dependencies are typically downloaded by the build system and used without modification. The license exception requests pertain to instances where **they are utilized in their unmodified form**.*
-  **Are there any alternative components available with equivalent functionality under a more permissive license?** 
    - *To the best of my knowledge, there are no compelling alternatives*.
-  **How do these component integrate with or interact with, if at all, other components of the project?**
    - *These components are required by the project either directly or transitively through other third-party components. For instance, [libbpf](https://github.com/libbpf/libbpf) (licensed under the BSD 2-clause and therefore automatically accepted on the Allowlist) depends on `libelf`. Typically, these components are linked into the project's programs by compilers during build time.*

**Comment by amye** [comment]
Clarification: 
`libelf` - is this statically or dynamically linked?

**Comment by leogr** [comment]
> Clarification: `libelf` - is this statically or dynamically linked?

Hey @amye 
It depends on the project. In Falco, `libelf` is statically linked.

**Comment by amye** [comment]
Ok, so in order to get an exception approved, we should scope this a little more. 
What's the scope of the exception requested -- just Falco's usage?

**Comment by leogr** [comment]
> Ok, so in order to get an exception approved, we should scope this a little more. What's the scope of the exception requested -- just Falco's usage?

As a Falco maintainer, I would like to request an exception, at least for  Falco's usage. In Falco, we use it to deal with the eBPF program used by Falco to collect data from the kernel. It's statically compiled inside the Falco binary. Also, `libbpf` (another 3rd party dependency for Falco, licensed under the BSD 2-clause and therefore automatically accepted on the Allowlist) depends on `libelf`. Let us know if you need any further information in this regard.

That being said, as a separate and optional request, I would suggest you consider a general exception for libelf since it may benefit some projects, too. 

Thanks

**Comment by richardfontana** [comment]
I'm a little confused by some of the example uses. Some of these look like packages installed in container images, but if that's what CNCF license policy covers, then it would have to have a blanket exception for GPLv2, GPLv3 and tons of other copyleft and non-copyleft licenses.

**Comment by leogr** [comment]
> I'm a little confused by some of the example uses. Some of these look like packages installed in container images, but if that's what CNCF license policy covers, then it would have to have a blanket exception for GPLv2, GPLv3 and tons of other copyleft and non-copyleft licenses.

Hey @richardfontana 

As a Falco maintainer, my insights are specific to Falco, where all three libraries mentioned above are statically linked during the build, not packaged in the container image. This requires only license exceptions specifically for their usage in Falco, not a blanket one. 

That said, I still think discussing GPL packages in container images is valuable, however, it's beyond this issue's scope, in my opinion. wdyt?

**Comment by amye** [comment]
Approved by the GB as of 2/12: 

- License exception for [libcurl](https://github.com/curl/curl)
- License exception for [uthash](https://github.com/troydhanson/uthash)
- License exception for [libelf](https://sourceware.org/elfutils/), but for dynamic linking only

**Comment by leogr** [comment]
Hey @Cmierly, should this be documented in https://github.com/cncf/foundation/tree/main/documents? :thinking:
