### ISSUE TITLE
Conflict in style guides

### ISSUE THREAD

**Issue by jkirklan** [cncf/foundation#64]
There are two versions of the style guide available:

https://www.cncf.io/blog/2018/09/04/the-cloud-native-computing-foundation-cncf-style-guide/
https://github.com/cncf/foundation/blob/master/style-guide.md

The style guide on github seems to be at least six months further along than the blog post.  The blog post comes up before the more current style guide on github.   I know the blog post was a snapshot in time, but it is confusing to users.  Can we either update the blog post or put a disclaimer in it to say that the current style guide is in github at the top? 

thanks!

**Comment by krook** [comment]
I put in a request to the team that manages CNCF blogs to add the disclaimer.

**Comment by krook** [comment]
The [disclaimer has been added](https://www.cncf.io/blog/2018/09/04/the-cloud-native-computing-foundation-cncf-style-guide/). Closing.
