### ISSUE TITLE
Question about usage of AI-assisted coding tools

### ISSUE THREAD

**Issue by flavio** [cncf/foundation#644]
Are there official guidelines from CNCF that regulate the usage of AI-assisted coding tools (e.g. GitHub Copilot, Amazon CodeWhisperer ...) when contributing to CNCF projects?

I couldn't find anything on this topic.

**Comment by joannalee333** [comment]
Hi @flavio, thanks for your question. The Linux Foundation will be issuing guidance very shortly (within the next couple of weeks) on how to use AI-assisted coding tools responsibly for contributing to LF (including CNCF) open source projects. So please stay tuned. I'll post a link here when the guidance goes live.

**Comment by amye** [comment]
https://www.linuxfoundation.org/legal/generative-ai is now public
