### ISSUE TITLE
[License Exception Request] Falco's kernel module

### ISSUE THREAD

**Issue by leogr** [cncf/foundation#645]
Hello,

[Recent discussions](https://github.com/cncf/toc/pull/956#issuecomment-1734195598) have highlighted the need for a license exception for kernel modules. Based on this, I'd like to kindly ask the CNCF to consider granting a license exception for [Falco's kernel module](https://github.com/falcosecurity/libs/blob/master/driver/main.c), which is dual licensed under _GPL-2.0-only OR MIT_.

On a side note: while this request centers on Falco, there might be value in thinking about similar considerations for other CNCF projects, purely for the broader community's benefit. This is just a thought and not a core part of this request.

I've also prepared a technical write-up to assist in reviewing this request: 
https://docs.google.com/document/d/1UJwtjsQFps3TsibKG0D4JEPi5plogMUT9LZz6xBhO-M/edit

cc @amye

Thanks,
Leo

**Comment by amye** [comment]
Approved by Governing Board on 2-27

**Comment by leogr** [comment]
Hey @amye 

Has this been documented? I couldn't find it. 

Thanks

**Comment by leogr** [comment]
> Hey @amye
> 
> Has this been documented? I couldn't find it.
> 
> Thanks

cc @Cmierly, should this be documented?
