### ISSUE TITLE
New Capsule project for sandbox onboarding 

### ISSUE THREAD

**Issue by maxgio92** [cncf/foundation#647]
Hi,
as part of the [Capsule project CNCF sandbox onboarding](https://github.com/cncf/toc/issues/971), this issue tracks the requirement of:
> Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it.

cc @amye @bsctl @prometherion @MaxFedotov @oliverbaehler

Thank you,
Massimiliano

**Comment by amye** [comment]
#971 in TOC repo is the right place for these.
