### ISSUE TITLE
Add new "beginners" channel to CNCF Slack

### ISSUE THREAD

**Issue by amye** [cncf/foundation#651]
**Background**
There are currently a lot of questions about how to get started contributing, how to learn more about devops, how to do Y in Z, etc. in many channels such as [#random](https://cloud-native.slack.com/messages/random), [#hallway](https://cloud-native.slack.com/messages/hallway), and [#mentoring](https://cloud-native.slack.com/messages/mentoring). While there are currently people answering these questions in the channels I've mentioned, it shows that there isn't a good place for beginners/newcomers to go and ask all their questions.

For more background, see the slack discussion [here](https://cloud-native.slack.com/archives/CT6CWS1JN/p1692113266748519)

**Proposal**
We should add a #beginners channel to the CNCF slack and make it one of the default channels which everyone is added. This channel would be the default place to ask questions like "how can I get started contributing". It will also be a good place where we can direct people to other channels. For example, if someone asks about how to contribute a Knative feature, we can direct them to the [#knative-contributors](https://cloud-native.slack.com/messages/knative-contributors) channel, and if someone wants to learn more about ArgoCD we can direct them to [#argo-cd](https://cloud-native.slack.com/messages/argo-cd).

Moving from https://github.com/cncf/toc/issues/1146 to here

**Comment by krook** [comment]
@castrojo FYI, related to the discussion we had yesterday

**Comment by krook** [comment]
FYI, @dims created a Slack channel related to this in November: #cncf-new-contributors

If it's not already, we should make this a default channel for new joiners.

**Comment by castrojo** [comment]
Do we want to send all new users to a contributor's channel? Or do we want to investigate something like a bot asking if they're there for tech support or for contributing?  

My concern is that #cncf-new-contributors would be immediately overrun with tech support questions.

**Comment by krook** [comment]
Why not both? 😸. 

I think if each default description is clear and has good pinned resources, it should work out well and may consolidate the new contributor questions to a single channel.

And this reminds me, I need to follow up with @jjasghar about his Slackbot implementation for handling FAQs.

**Comment by jjasghar** [comment]
Here to help however I can Dan!

**Comment by castrojo** [comment]
Hey JJ, wanna pair up and bust this out and you can show me the setup? We need to catch up anyway. 😄

**Comment by krook** [comment]
`#cncf-new-contributors` is now set as a default channel. If we do see an influx in off-topic support questions we can undo that. 

The other default channels we've had set for a while are `#general`, `#hallway`, and `#random`.
