### ISSUE TITLE
Update Clause 6.d.ii in the TOC charter to change "engineers" to "technologists"

### ISSUE THREAD

**Issue by monadic** [cncf/foundation#71]
Clause 6.d.ii in the TOC charter says:
"ii. demonstrate an advanced level of professional experience as
engineers in the scope of CNCF"

As the TOC looks after ALL aspects of projects, community, etc, not
just "engineering".... I propose that we change "engineers" to
"technologists".

There is a quorum of TOC votes in favour.

**Comment by dankohn** [comment]
I will propose to the GB for an email vote.

**Comment by mswilson** [comment]
Any update on this?

Also consider changing this at the very top of the CNCF Charter.

> These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust automation, they allow engineers to make high-impact changes frequently and predictably with minimal toil.

**Comment by xmulligan** [comment]
@krook do you know if this email vote ever happened?

**Comment by krook** [comment]
> @krook do you know if this email vote ever happened?

I don't. In any case @TheFoxAtWork has provided an update here: https://github.com/cncf/toc/issues/1351#issuecomment-2168359604

**Comment by joannalee333** [comment]
This change will be considered by the Governing Board at its upcoming meeting later this month

**Comment by krook** [comment]
Completed with https://github.com/cncf/foundation/pull/861
