### ISSUE TITLE
[License Exception Request] [kubernetes/kops] [MPL-2.0]

### ISSUE THREAD

**Issue by hakman** [cncf/foundation#741]
### Component details

github.com/hashicorp/memberlist

### License name

MPL-2.0

### Code modified?

Unmodified

### Changes contributed?

N/A

### Any alternatives?

The component does not have any alternative that we know of, but we plan to remove it in 2025.

### Integrates with other components?

Memberlist is the main component of the [Gossip DNS](https://github.com/kubernetes/kops/blob/master/docs/gossip.md) feature.

> Gossip-based clusters use a peer-to-peer network instead of externally hosted DNS for propagating the K8s API address. This means that an externally hosted DNS service is not needed.
> Gossip does not suffer potential disruptions due to out of date records in DNS caches as the propagation is almost instant.
> Gossip is also the only option if you want to deploy a cluster in any of the AWS regions without Route 53, such as the China and GovCloud ones.

**Comment by jeefy** [comment]
This exception has been approved as of July 16th, 2024 :) Closing this out!
