### ISSUE TITLE
[License Exception Request] Argo CD vs Redis SSPL

### ISSUE THREAD

**Issue by hairmare** [cncf/foundation#750]
### Component details

It's [Redis](https://redis.com) as per [their annoucement](https://redis.com/blog/redis-adopts-dual-source-available-licensing/).

### License name

SSPL

### Code modified?

In Argo CD's case, unmodified from (community) Docker Hub, i just [raised this in Argo CD's discussions](https://github.com/argoproj/argo-cd/discussions/17599).

Thusly, Argo CD currently deploys an unaffected 7.0 version of Redis, this issue is about preempting the upcoming change in >=7.4.

### Any alternatives?

i'm going to leave this question up to more qualified folks

### Integrates with other components?

lol yes,

i really don't expect this request to get granted, but we need to start discussing the impact of redis not being OSS anymore asap

**Comment by hairmare** [comment]
As an alternative to the [SSPL](https://en.wikipedia.org/wiki/Server_Side_Public_License) (aka MongoDB style) license, Redis is also provided under the (not  OSI approved) [Redis Source Available License 2.0](https://redis.com/legal/rsalv2-agreement/).

The first "concrete" and public results of the license change I found so far are in [gitlab.com/fedora/legal/fedora-license-data#497](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/497).

**Comment by amye** [comment]
In the intervening days, a new option has come up: https://github.com/valkey-io/valkey 

Would this solve the dependency?

**Comment by hairmare** [comment]
It seems likely that Valkey is going to be the way forward when replacing Redis to solve this dependency.

The Valkey communities work has been very impressive and it looks like we can expect a stable release in due time.

**Comment by hairmare** [comment]
i created a [grimoirelab report on cauldron.io](https://cauldron.io/project/8356) to gain further insights. here are some screenshots that visualize the rise of ValKey since the fork. I used the time range 2024-03-22 - 2024-04-18 to generate these. 

## ValKey

![screenshot showing commit and issue activity for ValKey](https://github.com/cncf/foundation/assets/116588/e88acf68-39ce-4265-aed5-7331605af39c)

ValKey ranges from a few to several commit per day with issues and review activity to match.

## Redis

![screenshot showing the same activity for redis](https://github.com/cncf/foundation/assets/116588/e4d5f394-e2b8-472d-9749-230a74712ece)

Redis has infrequent commits and they commit once daily at the most. Their issue created/closed values are similar to ValKey but there is much less review activity.

It's not surprising that Redis has fewer public contributions since the fork, if we look at redis/redis a year ago (2023-03-22 - 2023-04-18), we might get a more reasonable base line comparison

![and again for the last year about redis](https://github.com/cncf/foundation/assets/116588/17f64bb1-24bb-4253-a055-6ada31991c5b)

The commit activity from the same time frame in 2023 seems to match current ValKey activity. There was less review and issue activity compared to this year.

## Conclusion

I think these early numbers indicate that the ValKey project is off to a healthy start. The comparison to Redis Inc's contribution numbers is interesting, but doesn't provide more value than fancy graphics and should not be used for any decision making. Feel free to rummage through the data set yourself via the link provided above.

I believe it is still too early for our :crystal_ball: to provide proper insights into the future of Redis Inc's source-available offering. But I do think it is safe to say that there is no need for a license exception.

There is a clear direction for the near term that has been confirmed as the way forward in the [Argo CD discussion forum](https://github.com/argoproj/argo-cd/discussions/17599#discussioncomment-8951171) and ValKey's BSD-3-Clause license is already on the [CNCF Allowlist License Policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#cncf-allowlist-license-policy).

Given this does not need to go forward, I am closing it as not planned since there is no need to initialize the exception process at this time.
