### ISSUE TITLE
Google docs seem too wide open

### ISSUE THREAD

**Issue by raravena80** [cncf/foundation#76]
Any anonymous hacker can type anything on a bunch of TOC-SIG Google doc. I can basically type 'Anonymous was here' from an incognito window on these Google docs (and more):

- SIG-Security notes (Ironically 😄):
  - https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g
- SIG-Runtime notes:
  - https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk
- SIG-Network notes:
  - https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q
- etc

I'm wondering if there's a better way to 
- Keep track of users who make the changes
- Allow certain people who request access
- Allow anonymous to comment only, etc.

cc: @amye @quinton-hoole

**Comment by caniszczyk** [comment]
I transferred this issue to here as it doesn't belong in the TOC repo

**Comment by caniszczyk** [comment]
closing as this doesn't seem to be a huge issue and hasn't come up recently
