### ISSUE TITLE
Request: Avoid Scheduling KubeCon+CloudNativeCon During Ramadan, Eid

### ISSUE THREAD

**Issue by adowair** [cncf/foundation#770]
To the Cloud Native Computing Foundation,

We begin by thanking the CNCF for your efforts in making KubeCon+CloudNativeCon events inclusive by providing multi-faith prayer rooms. These accommodations are greatly appreciated by the Muslim cloud native community.

The holy month of Ramadan holds immense spiritual and cultural significance for Muslims worldwide. It is a period of fasting, increased devotion through prayers and charity, self-reflection, and strengthening family/community bonds. These observances constitute one of the Five Pillars of Islam, and are central to Muslim identity and practice.
Ramadan is followed by the 3-day Eid al-Fitr celebration, marking the end of the fasting period with feasting and gatherings.

## The Challenge
For Muslim professionals attending KubeCon+CloudNativeCon, having these major events overlap with Ramadan/Eid **(as was the case in [Paris 2024](https://kccnceu2024.sched.com/) and [Amsterdam 2023](https://kccnceu2023.sched.com))**, presents several key challenges:

- Maintaining energy levels and full participation while fasting from food/drink during the day
- For traveling attendees, lack of community/family support for breaking the daily fast in the evenings
- Inability to take part in social events that coincide with breaking the fast, especially those involving alcohol, compromising networking opportunities
- Difficulties fully observing religious obligations like additional prayers during Ramadan

## The Request
We understand changing announced dates is tough, but want to flag the potential overlap for the **April 1-4, 2025** conference in **London** with Ramadan and Eid (around March 1 - April 3, 2025).

**For 2026 and beyond, we're requesting that KubeCon+CloudNativeCon events avoid the full Ramadan and Eid periods to allow Muslim attendees to fully participate.**

As Ramadan and Eid follow the lunar Islamic calendar, their dates shift each year relative to the Gregorian calendar. I (@adowair) am available to work closely with the CNCF team to implement reasonable accommodations for scheduling.

The CNCF has been great about providing multi-faith prayer rooms, and avoiding scheduling conflicts with the fluctuating Ramadan/Eid dates would further demonstrate your commitment to an open, inclusive community. We appreciate your consideration on this matter.

## The Benefits
Accommodating the observance of Ramadan and Eid al-Fitr at KubeCon+CloudNativeCon events would greatly benefit the entire cloud native community. It would enable increased diversity by removing participation barriers for Muslim professionals. Their perspectives, expertise, and involvement would be more fully represented, in line with CNCF's values of openness and inclusion.

Muslim attendees who can wholeheartedly participate without conflicts would also become powerful ambassadors for these events within their communities afterward. This positive experience would inspire them to enthusiastically promote CNCF's work and encourage future attendance.

Thank you,
The Muslim cloud native community and allies

---
### Call to Action
We invite all Muslim KubeCon attendees, prospective attendees, and allies to

- Sign the petition (react with ❤️)
- Comment your CNCF affiliation, and how this issue impacts you, below
- Share widely! Use social media to bring attention to this issue

We appreciate you showing your support for greater accommodation and inclusivity at these events. Discussions in the thread are welcome!

**Comment by hhemied** [comment]
Very innovative idea to open such a case.
It was a bit hard this year for me specially with organizing such a big day like platform engineering day.
We are looking forward to a positive action from the CNCF side.

Thanks again for that.

**Comment by barry110986** [comment]
I really appreciated the availability of prayer rooms. It is a strong message about how CNCF manage to include everybody ! However, as Ali pointed out, it is difficult as a muslim to fully take part in any type of event during Ramadan.

**Comment by helayoty** [comment]
Thank you, @adowair, for bringing this topic up. I had a quick discussion last year with a few TOC members and with the CNCF management team, but unfortunately, there has been no result so far. I hope this can be taken into consideration for the planning along with Diwali as well.

**Comment by asem-hamid** [comment]
@adowair Thank you for bringing attention to this important issue. Your efforts to address the challenges faced by Muslim professionals during KubeCon+CloudNativeCon events are commendable, and I stand in full support of accommodating Ramadan and Eid al-Fitr to ensure equal participation opportunities. We eagerly anticipate a positive response from the CNCF.

**Comment by essamgouda97** [comment]
Thank you for bringing that issue under one umbrella, the muslin community is a big part of the org and accommodating us would be very thoughtful !

**Comment by caniszczyk** [comment]
Thank you for sharing the detailed explanation of why it’s important not to overlap with the Ramadan holiday. CNCF values diversity and inclusivity in our events and we strive to avoid overlaps whenever possible. The date selection process for KubeCon + CloudNativeCon and other CNCF events involves a thoughtful process to minimize conflicts for a diverse set of attendees. We take into consideration religious observances, local holidays, as well as other industry events when evaluating venue and date options. It's a tough puzzle at times, especially when conference venue space is limited (at our size). 

Eid al-Fitr is on our list of observances to take into consideration, however we were not aware that it is a 3-day celebration based on the calendar we used. Several online calendars indicate one day of observance and for 2025 the observance date is listed as March 30 or March 31. Based on this information, we did not believe there was an overlap which it sounds like is incorrect. Unfortunately, there is no way to move the 2025 event dates or venue, but I am happy to report that for 2026 - 2028 there is no overlap with Ramadan, including the 3 days of observance for Eid al-Fitr, and we will be sure to be mindful of the 3 days for all future bookings. The dates for 2026 have been announced (March 23-26, 2026 | Amsterdam) and CNCF will announce the 2027 & 2028 dates later this year.

If affected community members are unable to join KubeCon + CloudNativeCon Europe 2025, April 1-4 in London, we hope that attending one of our other KubeCon + CloudNativeCon events is possible.

I hope this helps you understand things a bit more and we do plan on doing a CNCF blog post in the future of how kubecon planning works in some more detail.

**Comment by abuango** [comment]
Thank you @caniszczyk and the CNCF team, for your thoughtfulness and inclusion efforts. I was delighted to see a prayer room in Paris and its close proximity to the restroom, this showed that a lot of thought was put into making it happen.

**Comment by adowair** [comment]
Thank you @caniszczyk for the detailed response. We appreciate your attention and intention. It's great to know that Eid al-Fitr was already accounted for, and I'm glad we were able to communicate that it is indeed a 3-day observance.

We'd also like to request your consideration to account for the _month of Ramadan proper_ when scheduling, as it is **during** the month which challenges above (fasting, breaking the fast, additional religious obligations) manifest.

I recognize that 30 extra days of blackout is non-trivial, and as such we completely understand that other factors (say, other holidays) will, and should, take precedence in scheduling. We appreciate your consideration on the matter, and are hoping to reach an agreement that satisfies everyone in the community.

**Comment by caniszczyk** [comment]
Thanks @adowair 

We will definitely account for the whole month of Ramadan when planning in the future, but can't make any guarantees that there may not be overlap in the future over the whole month. I hope based on what was said in the previous thread https://github.com/cncf/foundation/issues/770#issuecomment-2048217360 and our plans for 2026/2027, things are in a better place than they were before.

I'll close this thread for now, but in the future, if you have any questions on LF/CNCF events, you can reach out to events@cncf.io and see the https://events.linuxfoundation.org for full schedule.

**Comment by adowair** [comment]
Fantastic @caniszczyk—that makes sense and is exactly what we hoped for. I appreciate your continued attention to making CNCF events a success for everyone. Thank you, as well, to everyone who commented or reacted to show support. 

Until the next conference!
