### ISSUE TITLE
Hyphenated “microservices” in the cncf charter

### ISSUE THREAD

**Issue by dantwining** [cncf/foundation#8]
1b of the charter refers to “micro-services” (sic) whereas the FAQ and front page both refer to the (generally accepted as correct) form “microservices”. Please could the charter be corrected? I would happily raise a PR, but cannot find it in a repo.

https://www.cncf.io/about/charter/

**Comment by dankohn** [comment]
Thanks for raising this. We're aiming to replace both uses of
"micro-services" with a reference to
https://github.com/cncf/toc/blob/master/DEFINITION.md but it may take a
couple more months for the CNCF governing board to approve the change. I
totally agree that we should do it, though.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dantwining** [comment]
I think this can be closed now, as the charter has been updated and references the “microservice” version of the definition. So I’ll close it! Thanks.
