### ISSUE TITLE
[License Exception Request] [kubernetes-sigs/gateway-api] [MIT]

### ISSUE THREAD

**Issue by robscott** [cncf/foundation#809]
### Component details

We're making modifications to mkdocs-material templates that are MIT licensed in https://github.com/kubernetes-sigs/gateway-api/pull/3132. This is all actually in an attempt to meet CNCF trademark guidelines 😄, so we're unlikely to be the only ones to run into this. In a [recent Slack thread](https://kubernetes.slack.com/archives/C1TU9EB9S/p1717616676425929?thread_ts=1717613057.828109&cid=C1TU9EB9S) I was encouraged to formally ask for an exception via this process.

### License name

MIT

### Code modified?

Yes, some snippets will be modified, see https://github.com/kubernetes-sigs/gateway-api/pull/3132/files for an example.

### Changes contributed?

Not applicable - we're making modifications that are unique to our docs following the recommendations of mkdocs-material.

### Any alternatives?

There are some, but this is one of the easiest tools to use, and is already [widely used within the k8s ecosystem](https://cs.k8s.io/?q=mkdocs-material&i=nope&files=&excludeFiles=&repos=).

- kubernetes-sigs / aws-load-balancer-controller
- kubernetes-sigs / network-policy-api
- kubernetes-sigs / cri-tools
- kubernetes-sigs / gateway-api
- kubernetes-sigs / security-profiles-operator
- kubernetes / cloud-provider-aws
- kubernetes / ingress-nginx
- kubernetes-sigs / external-dns
- kubernetes-sigs / sig-multicluster-site

### Integrates with other components?

Not applicable, just used for documentation.

**Comment by robscott** [comment]
Any updates on this?

**Comment by krook** [comment]
The email vote concluded in October and the CNCF Governing Board has approved this exception request for this.
