### ISSUE TITLE
[License Exception Request] Connect: allow OpenSSL license for swift-nio-ssl

### ISSUE THREAD

**Issue by akshayjshah** [cncf/foundation#823]
### Component details

The component is [`swift-nio-ssl`](https://github.com/apple/swift-nio-ssl), part of Swift's non-blocking networking stack, at the most recent version. (All versions I checked have the same problem, but let's focus on the latest version.)

The repository is https://github.com/apple/swift-nio-ssl. The repository as a whole claims to be [available under an Apache 2 license](https://github.com/apple/swift-nio-ssl/blob/main/LICENSE.txt), but it [includes code that's licensed under the OpenSSL license](https://github.com/apple/swift-nio-ssl/blob/main/Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv8-ios.ios.aarch64.S#L9). The text in that file also allows use under the CRYPTOGAMS license or GPL v2.

### License name

OpenSSL

### Code modified?

Unmodified

### Changes contributed?

N/A

### Any alternatives?

As far as I know, `swift-nio-ssl` is the only way to use HTTP/2 + TLS _and have access to HTTP trailers_ on iOS.

### Integrates with other components?

`connect-swift` is an RPC library that's part of the broader Connect project, which recently joined the CNCF Sandbox. `swift-nio-ssl` is a build-time dependency of the `connect-swift` subpackage that offers gRPC compatibility.

**Comment by akshayjshah** [comment]
For context, `connect-swift-ssl` is also used in gRPC's Swift implementation: https://github.com/grpc/grpc-swift/blob/main/Package.swift#L81.

**Comment by krook** [comment]
The CNCF Governing Board has approved this exception request in an October vote.
