### ISSUE TITLE
GitHub Enterprise Banner for KubeCon

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#863]
GitHub has the ability to set banners https://github.com/enterprises/cncf/settings/announcement

![Image](https://github.com/user-attachments/assets/978789c1-b1d1-498d-a485-2016b74051dc)

Just like we have a banner for KubeCon on kubernetes.io 6 weeks out from the conference, we will add one to GitHub to remind people of the event across CNCF project repository sites.

The message will be: 

🎉 Join us for three days of incredible opportunities to collaborate and learn at KubeCon + CloudNativeCon: https://hubs.ly/Q02RyVHF0

**Comment by jeefy** [comment]
Messaging LGTM

**Comment by caniszczyk** [comment]
And it's live now: 

![Image](https://github.com/user-attachments/assets/f58a36f4-4d04-4d60-9f02-644c5cebe5ec)
