### ISSUE TITLE
Extend videos.cncf.io to include more videos

### ISSUE THREAD

**Issue by caniszczyk** [cncf/foundation#87]
via Liz Rice

"Tried out the Explore Videos tool - would be great if this was extended back to all the KubeCon videos not just 2019!"

**Comment by krook** [comment]
The videos.cncf.io subdomain no longer exists. The link to Videos in the cncf.io nav under Blog & News now links to the [CNCF YouTube channel](https://www.youtube.com/c/cloudnativefdn) which has all our event videos.
