### ISSUE TITLE
Rename the whitelist policy 

### ISSUE THREAD

**Issue by alejandrox1** [cncf/foundation#93]
The CNCF has a whitelist policy: https://github.com/cncf/foundation/blob/master/whitelist-policy.md.
Associating "white" with good or allowed has implications of systematic racism.
Using another name (e.g., licence allowed list) would better describe the policy.
I think https://developers.google.com/style/inclusive-documentation#features-and-users could serve as a good reference here.

**Comment by caniszczyk** [comment]
thanks, we will take care of this

**Comment by caniszczyk** [comment]
done

https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md

**Comment by alejandrox1** [comment]
Thank you @caniszczyk !!
And that was super fast!
